### Send OTP
POST http://localhost:4000/api/auth/otp
Content-Type: application/json

{
  "phone": "+8801700000000",
  "name": "Shahriar",
  "role": "customer"
}

### Verify OTP
POST http://localhost:4000/api/auth/verify
Content-Type: application/json

{
  "phone": "+8801700000000",
  "otp": "123456"
}
